modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/spoorn/SpoornWeaponAttributes/issues"
license = "MIT"

[[mods]]
modId = "spoornweaponattributes"
version = "${version}"
displayName = "Spoorn Weapon Attributes"
authors = "spoorn"
description = '''
Adds randomized weapon attributes
'''
#logoFile = ""

[[dependencies.spoornweaponattributes]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spoornweaponattributes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spoornweaponattributes]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "NONE"
side = "CLIENT"